name: makentuapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2

  english_words: ^4.0.0
  provider: ^6.0.0
  clock: ^1.1.1
  slide_digital_clock: ^1.0.3
  syncfusion_flutter_charts: ^25.1.40
  expansion_tile_group: ^1.2.4
  sqflite: ^2.3.3
  path: ^1.9.0
  mongo_dart: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SFDigitalReadout
      fonts:
        - asset: assets/fonts/SFDigitalReadout-Light.ttf